
INCDIR += $(shell pkg-config --cflags libxml-2.0) -I./mavlink -I./ -I./wifibc/ -lpcap -DTELEMTRY_BRIDGE=1
LIBS += $(shell pkg-config --libs libxml-2.0)


INCDIR += $(shell pkg-config --cflags sdl)
LIBS += $(shell pkg-config --libs sdl)
LIBS += -ludev


all:
	gcc -o wifibc-tx wifibc/wifibc-tx.c wifibc/fec.c wifibc/lib.c mavlink/my_mavlink.c mavlink/my_mavlink_rewrite.c serial.c $(INCDIR) $(LIBS)


