.TH MULTIGCS 1
.SH NAME
multigcs \- multi protocol, multi platform Ground-Control-Station
.SH SYNOPSIS
.B multigcs
.RI "[-c SERVER_IP]"
.SH DESCRIPTION
This manual page documents briefly the
.B multigcs
command.
.PP
.B multigcs
is a multi protocol, multi platform Ground-Control-Station

.I multigcs 
needs a running X11 session an Open-GL support.

.SH OPTIONS
.I multigcs supports the following options:
.TP
.B \-c SERVER_IP
running in client mode, connectiong to 
.B SERVER_IP
.SH USAGE EXAMPLES
.TP
.B # multigcs
to run in normal/server mode
.TP
.B # multigcs -s 192.168.1.10
to connect to 192.168.1.10 in client mode
.SH AUTHOR
.B multigcs
was written by Oliver Dippel <oliver@multixmedia.org>.
.PP
This manual page was written by Oliver Dippel <oliver@multixmedia.org>
